server:
  port: 8084
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/tcc_stock?useUnicode=true&characterEncoding=utf8
        username: root
        password:


mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.inventory.api.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: debug
        org.dromara.hmily.demo.bonuspoint: debug
        org.dromara.hmily.demo.lottery: debug
        org.dromara.hmily.demo: debug
    path: "./logs"

