server:
  port: 8087
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.98:3306/tcc_order?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456

hmily:
    tcc :
        serializer : kryo
        recoverDelayTime : 128
        retryMax : 30
        scheduledDelay : 128
        scheduledThreadMax :  10
        repositorySupport : db
        started: true
        async-threads: 32
        tccDbConfig :
                 driverClassName  : com.mysql.jdbc.Driver
                 url :  jdbc:mysql://192.168.1.98:3306/tcc?useUnicode=true&amp;characterEncoding=utf8
                 username : root
                 password : 123456

        #repositorySupport : redis
        #tccRedisConfig:
                # masterName: mymaster
                 #sentinel : true
                 #sentinelUrl : 192.168.1.91:26379;192.168.1.92:26379;192.168.1.93:26379
                # password  : foobaredbbexONE123

mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.order.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.hmily.tcc.bonuspoint: info
        com.hmily.tcc.lottery: info
        com.hmily.tcc: info
        io.netty: info
    path: "./logs"

