server:
  port: 8883
  address: 0.0.0.0
  servlet:
    context-path: /inventory-service

spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/hmily_stock?useUnicode=true&characterEncoding=utf8
        username: root
        password:
    application:
      name: inventory-service

mybatis:
  type-aliases-package: org.dromara.hmily.demo.common.inventory.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
 instance:
   prefer-ip-address: true

inventory-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: debug
        org.dromara.hmily.demo.bonuspoint: debug
        org.dromara.hmily.demo.lottery: debug
        org.dromara.hmily.demo: debug
        io.netty: info
    path: "./logs"


