server:
  port: 8885
  address: 0.0.0.0
  servlet:
    context-path: /account-service


spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/tcc_account?useUnicode=true&characterEncoding=utf8
        username: root
        password:
    application:
      name: account-service
    main:
        allow-bean-definition-overriding: true

org:
    dromara:
         hmily :
            app-name: sc-account
            serializer : kryo
            recoverDelayTime : 128
            retryMax : 30
            scheduled-recovery-delay: 60
            scheduledThreadMax :  10
            repository : mysql
            hmilyDbConfig :
                 driverClassName  : com.mysql.jdbc.Driver
                 url: jdbc:mysql://127.0.0.1:3306/hmily?useUnicode=true&characterEncoding=utf8
                 username : root
                 password :



      # repositorySupport : redis
       #         hostName  : 192.168.1.68
       #         port      :  6379
       #         password  :


       # repositorySupport : zookeeper
       #         host      : 92.168.1.73:2181
       #         sessionTimeOut      :  100000
       #         rootPath  : /tcc

#            hmilyMongoConfig :
#              mongoDbUrl  : 127.0.0.1:27017
#              mongoDbName  :  admin
#              mongoUserName  : root
#              mongoUserPwd   : 123456

       # repositorySupport : file
       #         path      : /account
       #         prefix    :  account

mybatis:
  type-aliases-package: org.dromara.hmily.demo.springcloud.account.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
 instance:
   prefer-ip-address: true

account-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.dromara.hmily.bonuspoint: debug
        org.dromara.hmily.lottery: debug
        org.dromara.hmily: debug
        io.netty: info
    path: "./logs"

