server:
  port: 8885
  address: 0.0.0.0
  servlet:
    context-path: /account-service


spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/soul-open?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&failOverReadOnly=false&autoReconnect=true
        username: root
        password: dev-mysql-R3ND7N4zvjYt0Wvw
    application:
      name: account-service
    main:
        allow-bean-definition-overriding: true

org:
    dromara:
         hmily :
            serializer : kryo
            recoverDelayTime : 128
            retryMax : 30
            scheduledDelay : 128
            scheduledThreadMax :  10
            repositorySupport : db
            started: false
            hmilyDbConfig :
                 driverClassName  : com.mysql.jdbc.Driver
                 url: jdbc:mysql://rm-bp10o39k37lfxh090.mysql.rds.aliyuncs.com:3306/soul-open?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&failOverReadOnly=false&autoReconnect=true
                 username : root
                 password : dev-mysql-R3ND7N4zvjYt0Wvw

       # repositorySupport : redis
       #         hostName  : 192.168.1.68
       #         port      :  6379
       #         password  :


       # repositorySupport : zookeeper
       #         host      : 92.168.1.73:2181
       #         sessionTimeOut      :  100000
       #         rootPath  : /tcc

       # repositorySupport : mongodb
       #       mongoDbUrl  : 192.168.1.68:27017
       #       mongoDbName  :  happylife
       #       mongoUserName  : xiaoyu
       #       mongoUserPwd   : 123456

       # repositorySupport : file
       #         path      : /account
       #         prefix    :  account

mybatis:
  type-aliases-package: org.dromara.hmily.demo.springcloud.account.entity
  config-location: classpath:mybatis/mybatis-config.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
 instance:
   prefer-ip-address: true

account-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.dromara.hmily.bonuspoint: debug
        org.dromara.hmily.lottery: debug
        org.dromara.hmily: debug
        io.netty: info
    path: "./logs"

