server:
  port: 8085
  contextPath: /
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.68:3306/tcc_account?useUnicode=true&characterEncoding=utf8
        username: xiaoyu
        password: Wgj@555888

hmily:
    tcc :
        serializer : kryo
        recoverDelayTime : 128
        retryMax : 30
        scheduledDelay : 128
        scheduledThreadMax :  10
        repositorySupport : db
        tccDbConfig :
                 driverClassName  : com.mysql.jdbc.Driver
                 url :  jdbc:mysql://192.168.1.68:3306/tcc?useUnicode=true&amp;characterEncoding=utf8
                 username : xiaoyu
                 password : Wgj@555888

       # repositorySupport : redis
       #         hostName  : 192.168.1.68
       #         port      :  6379
       #         password  :


       # repositorySupport : zookeeper
       #         host      : 92.168.1.73:2181
       #         sessionTimeOut      :  100000
       #         rootPath  : /tcc

       # repositorySupport : mongodb
       #       mongoDbUrl  : 192.168.1.68:27017
       #       mongoDbName  :  happylife
       #       mongoUserName  : xiaoyu
       #       mongoUserPwd   : 123456

       # repositorySupport : file
       #         path      : /account
       #         prefix    :  account


mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.account.api.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.hmily.tcc.bonuspoint: info
        com.hmily.tcc.lottery: debug
        com.hmily.tcc: debug
        io.netty: info

    path: "./logs"

