server:
  port: 8087
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/tcc_order?useUnicode=true&characterEncoding=utf8
        username: root
        password:

mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.order.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.dromara.hmily.bonuspoint: info
        org.dromara.hmily.lottery: info
        org.dromara.hmily: info
        io.netty: info
    path: "./logs"

